apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: todoapp
          image: joveful/todo-app4
          volumeMounts:
            - name: shared-image
              mountPath: /app/data
          env:
          - name: PORT
            value: "3000"
          - name: API_URL
            value: "http://localhost:8081/todos"