apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-backend-config
  namespace: project
data:
  PORT: "4000"
  PGHOST: postgres-svc
  PGPORT: "5432"
  PGDATABASE: todos
  PGUSER: postgres
  PGPASSWORD: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todobackend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todobackend
  template:
    metadata:
      labels:
        app: todobackend
    spec:
      containers:
        - name: todoapp
          image: joveful/todo-backend2
          envFrom:
          - configMapRef:
              name: todo-backend-config