apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: log-output
          image: joveful/log-writer1
          volumeMounts:
          - name: shared-image
            mountPath: /usr/src/app/files
        - name: log-server
          image: joveful/log-server4
          volumeMounts:
          - name: shared-image
            mountPath: /usr/src/app/files